# Generated by Django 4.2.3 on 2023-09-20 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Claims',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liability_claim_percentage', models.FloatField(null=True)),
                ('third_party_policy', models.CharField(max_length=255, null=True)),
                ('fraud', models.BooleanField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(default='', max_length=255)),
                ('image', models.ImageField(default=None, null=True, upload_to='uploads')),
                ('price', models.FloatField()),
                ('quantity', models.IntegerField(null=True)),
                ('status', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='account_status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10),
        ),
        migrations.AddField(
            model_name='client',
            name='address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='dob',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='phone_number',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='role',
            field=models.CharField(choices=[('general_user', 'general_user'), ('admin', 'admin'), ('authority', 'authority'), ('staff', 'staff'), ('investigator', 'investigator')], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='user_image',
            field=models.ImageField(default=None, null=True, upload_to='uploads'),
        ),
        migrations.AlterField(
            model_name='client',
            name='client_confirm_password',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='client_password',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='client_info',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='client_info',
            name='email',
            field=models.EmailField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='client_info',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='Vehicle_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(null=True)),
                ('weight', models.CharField(max_length=255, null=True)),
                ('color', models.CharField(max_length=255, null=True)),
                ('vehicle_age', models.FloatField(null=True)),
                ('claim_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.claims')),
            ],
        ),
        migrations.CreateModel(
            name='Driver_info',
            fields=[
                ('vehicle_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, null=True)),
                ('age', models.FloatField(null=True)),
                ('zip_code', models.CharField(max_length=255, null=True)),
                ('number_of_claims_five_years', models.IntegerField(null=True)),
                ('marital_status', models.CharField(max_length=255, null=True)),
                ('living_status', models.CharField(max_length=255, null=True)),
                ('address_change', models.CharField(max_length=255, null=True)),
                ('claim_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.claims')),
            ],
        ),
        migrations.CreateModel(
            name='Accident_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('witness', models.BooleanField(null=True)),
                ('accident_loaction', models.CharField(max_length=255, null=True)),
                ('claim_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.claims')),
                ('vehicle_id', models.ForeignKey(max_length=255, on_delete=django.db.models.deletion.CASCADE, to='myapp.driver_info')),
            ],
        ),
    ]
