# Generated by Django 4.2.3 on 2023-09-21 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_claims_product_client_account_status_client_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle_info',
            name='vehicle_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myapp.driver_info'),
        ),
    ]
