# Generated by Django 4.2.3 on 2023-10-01 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_order_invoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=100, null=True)),
                ('item_price', models.CharField(max_length=100, null=True)),
                ('total', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('transaction_number', models.CharField(max_length=255, null=True)),
                ('phone_number', models.CharField(max_length=255, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='invoice',
            name='customer_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='gateway',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
