# Generated by Django 4.2.3 on 2023-09-23 16:51

from django.db import migrations
from django.db import models

class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_claims_driver_info_product_client_account_status_and_more'),
    ]

    operations = [
       
        migrations.AddField(
            model_name='claims',
            name='policy_channel',
            field=models.CharField()
        ),
    ]
