# Generated by Django 4.2.3 on 2023-10-03 18:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_cart_payment_invoice_customer_name_invoice_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='id',
            field=models.TimeField(default=datetime.datetime(2023, 10, 4, 0, 29, 42, 477512), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cart',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
