# Generated by Django 4.2.3 on 2023-10-03 18:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_remove_cart_id_alter_cart_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='id',
            field=models.DateField(default=datetime.datetime(2023, 10, 4, 0, 37, 5, 604804), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cart',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
