# Generated by Django 4.2.3 on 2023-10-09 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_admin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='admin',
        ),
    ]
