# Generated by Django 4.2.3 on 2023-10-31 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_contact_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_message',
            name='message',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
