# Generated by Django 4.2.3 on 2023-10-31 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_alter_contact_message_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact_message',
            name='message_posted',
            field=models.DateField(null=True),
        ),
    ]
