# Generated by Django 4.2.3 on 2023-11-03 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_cart_order_id_payment_order_id_alter_order_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
