# Generated by Django 4.2.3 on 2023-11-27 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_alter_invoice_invoice_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='claims',
            name='probability',
            field=models.FloatField(null=True),
        ),
    ]
